In [1]:
import numpy as np
import torch

In [39]:
F = np.array([[4,2,0.6],[4.2, 2.1, 0.59],[3.9, 2.0, 0.58],[4.3, 2.1, 0.62],[4.1, 2.2, 0.63]])
F

array([[4.  , 2.  , 0.6 ],
       [4.2 , 2.1 , 0.59],
       [3.9 , 2.  , 0.58],
       [4.3 , 2.1 , 0.62],
       [4.1 , 2.2 , 0.63]])

In [5]:
Mean_F = np.mean(F,axis=0)
Mean_F

array([4.1  , 2.08 , 0.604])

In [7]:
Mean_centered_F = F-Mean_F
Mean_centered_F

array([[-0.1  , -0.08 , -0.004],
       [ 0.1  ,  0.02 , -0.014],
       [-0.2  , -0.08 , -0.024],
       [ 0.2  ,  0.02 ,  0.016],
       [ 0.   ,  0.12 ,  0.026]])

In [25]:
cov_matrix = np.cov(Mean_centered_F.T)
cov_matrix

array([[0.025  , 0.0075 , 0.00175],
       [0.0075 , 0.007  , 0.00135],
       [0.00175, 0.00135, 0.00043]])

In [28]:
e_v,e_vec = np.linalg.eig(cov_matrix)
e_vec

array([[ 0.93676841,  0.34958469, -0.0159843 ],
       [ 0.34148069, -0.92313136, -0.1766902 ],
       [ 0.0765238 , -0.16005947,  0.98413672]])

In [38]:
e_v

array([0.02787694, 0.00439387, 0.0001592 ])

In [40]:
res = np.dot(Mean_centered_F,e_vec[:,:2])
res

array([[-0.12130139,  0.03953228],
       [ 0.09943512,  0.01873667],
       [-0.21650871,  0.007775  ],
       [ 0.19540768,  0.04889336],
       [ 0.0429673 , -0.11493731]])

In [37]:
principal_components = pca.fit_transform(Mean_centered_F)
principal_components

array([[-0.12130139, -0.03953228],
       [ 0.09943512, -0.01873667],
       [-0.21650871, -0.007775  ],
       [ 0.19540768, -0.04889336],
       [ 0.0429673 ,  0.11493731]])

In [26]:
FT_F = np.dot(Mean_centered_F.T,Mean_centered_F)
FT_F

array([[0.1    , 0.03   , 0.007  ],
       [0.03   , 0.028  , 0.0054 ],
       [0.007  , 0.0054 , 0.00172]])

In [30]:
cov_FT_F = (1/5)*FT_F
cov_FT_F

array([[0.02    , 0.006   , 0.0014  ],
       [0.006   , 0.0056  , 0.00108 ],
       [0.0014  , 0.00108 , 0.000344]])

In [31]:
eig_val,eig_vec = np.linalg.eig(cov_FT_F)
eig_val

array([0.02230155, 0.00351509, 0.00012736])

In [36]:
eig_vec[:,:2]

array([[ 0.93676841,  0.34958469],
       [ 0.34148069, -0.92313136],
       [ 0.0765238 , -0.16005947]])

In [21]:
Result = np.dot(F,eig_vec[:,:2])
Result

array([[ 4.47594928, -0.54395965],
       [ 4.69668579, -0.56475525],
       [ 4.38074197, -0.57571693],
       [ 4.79265835, -0.53459857],
       [ 4.64021798, -0.69842923]])

In [12]:
from sklearn.decomposition import PCA

In [13]:
pca = PCA(n_components=2)

In [41]:
pca.explained_variance_ratio_

array([0.8596033 , 0.13548767])

In [43]:
var1 = np.dot(res[:,0],res[:,1])
var1

1.5612511283791264e-17

In [44]:
total_egnvalues = sum(eig_val)
var_exp = [(i/total_egnvalues) for i in sorted(eig_val, reverse=True)]

In [45]:
var_exp

[0.8596032995037316, 0.1354876678039723, 0.004909032692295956]

In [46]:
total_egnvalues

0.025944000000000005